// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/**
 * Stage 1 required checkpoint: "Cross-language signed-type hash vectors, including wrong-domain
 * and changed-field rejection expectations." This file independently recomputes EIP-712 digests
 * in Solidity (via Eip712HashHarness, which does not import packages/domain or OpenZeppelin's
 * EIP712 base) for the exact same fixture field values used by
 * packages/domain/test/fixtures.ts, and compares against the TypeScript-computed
 * `expectedDigest` values checked into docs/implementation/evidence/eip712-vectors.json
 * (generated by `pnpm vectors:generate`, see packages/domain/scripts/generate-vectors.ts).
 *
 * Run `pnpm vectors:generate` before this test — it fails clearly (not silently) if the
 * evidence file is missing.
 */

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {Eip712HashHarness} from "../src/test-harness/Eip712HashHarness.sol";

contract Eip712VectorsTest is Test {
    using stdJson for string;

    Eip712HashHarness internal harness;

    // Matches packages/domain/test/fixtures.ts TEST_DOMAIN exactly. These are deliberately
    // plain-repeated-byte patterns (0xf1f1...f1), not real checksummed addresses, so a bare
    // 40-hex-digit literal trips Solidity's EIP-55 checksum lint. Per the compiler's own
    // suggested workaround, a leading '00' byte (42 hex digits total) stops the literal from
    // being parsed as an address shape at all; uint160(...) then truncates to the low 160 bits,
    // which is the exact same value since the prepended byte is zero.
    uint256 internal constant CHAIN_ID = 31337;
    address internal constant VERIFYING_CONTRACT =
        address(uint160(0x00f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1));
    uint256 internal constant WRONG_CHAIN_ID = 1;
    address internal constant WRONG_VERIFYING_CONTRACT =
        address(uint160(0x00f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2));

    string internal evidenceJson;

    function setUp() public {
        harness = new Eip712HashHarness();
        string memory path = string.concat(vm.projectRoot(), "/../../docs/implementation/evidence/eip712-vectors.json");
        require(vm.exists(path), "eip712-vectors.json missing: run `pnpm vectors:generate` first");
        evidenceJson = vm.readFile(path);
    }

    function _fixtureInvoice() internal pure returns (Eip712HashHarness.Invoice memory) {
        return Eip712HashHarness.Invoice({
            invoiceId: 0x1111111111111111111111111111111111111111111111111111111111111111,
            merchantId: 0x2222222222222222222222222222222222222222222222222222222222222222,
            recipient: address(uint160(0x00a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1)),
            settlementToken: address(uint160(0x00b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1)),
            outputAmount: 500000,
            category: 3,
            validUntil: 2000000000
        });
    }

    function _fixtureInvoiceChangedAmount() internal pure returns (Eip712HashHarness.Invoice memory invoice) {
        invoice = _fixtureInvoice();
        invoice.outputAmount = 500001;
    }

    function _fixtureIntent() internal pure returns (Eip712HashHarness.PaymentIntent memory) {
        return Eip712HashHarness.PaymentIntent({
            policyId: 0x3333333333333333333333333333333333333333333333333333333333333333,
            invoiceHash: 0x4444444444444444444444444444444444444444444444444444444444444444,
            routeId: 0x5555555555555555555555555555555555555555555555555555555555555555,
            maxInputAmount: 2600000000000000,
            nonce: 1,
            validUntil: 2000000000,
            subsidyMode: 0, // NONE
            maxSubsidyAmount: 0
        });
    }

    function _fixtureApproval() internal pure returns (Eip712HashHarness.ExceptionApproval memory) {
        return Eip712HashHarness.ExceptionApproval({
            intentHash: 0x6666666666666666666666666666666666666666666666666666666666666666,
            nonce: 12345,
            validUntil: 2000000000
        });
    }

    function _fixtureApprovalChangedNonce() internal pure returns (Eip712HashHarness.ExceptionApproval memory a) {
        a = _fixtureApproval();
        a.nonce = 12346;
    }

    // --- Cross-language agreement: TS (viem hashTypedData) vs Solidity (hand-rolled) ---

    function test_InvoiceDigest_MatchesTypeScriptVector() public view {
        bytes32 solidityDigest = harness.hashInvoice(CHAIN_ID, VERIFYING_CONTRACT, _fixtureInvoice());
        bytes32 tsDigest = evidenceJson.readBytes32(".vectors.invoice.expectedDigest");
        assertEq(solidityDigest, tsDigest, "Solidity and TypeScript Invoice digests diverge");
    }

    function test_IntentDigest_MatchesTypeScriptVector() public view {
        bytes32 solidityDigest = harness.hashIntent(CHAIN_ID, VERIFYING_CONTRACT, _fixtureIntent());
        bytes32 tsDigest = evidenceJson.readBytes32(".vectors.intent.expectedDigest");
        assertEq(solidityDigest, tsDigest, "Solidity and TypeScript PaymentIntent digests diverge");
    }

    function test_ApprovalDigest_MatchesTypeScriptVector() public view {
        bytes32 solidityDigest = harness.hashApproval(CHAIN_ID, VERIFYING_CONTRACT, _fixtureApproval());
        bytes32 tsDigest = evidenceJson.readBytes32(".vectors.approval.expectedDigest");
        assertEq(solidityDigest, tsDigest, "Solidity and TypeScript ExceptionApproval digests diverge");
    }

    // --- Negative cases: wrong-domain / changed-field must NOT match the base vector ---

    function test_ChangedInvoiceAmount_DoesNotMatchBaseVector() public view {
        bytes32 base = evidenceJson.readBytes32(".vectors.invoice.expectedDigest");
        bytes32 changed = harness.hashInvoice(CHAIN_ID, VERIFYING_CONTRACT, _fixtureInvoiceChangedAmount());
        assertTrue(changed != base, "changed outputAmount produced the same digest as the base invoice");
    }

    function test_ChangedApprovalNonce_DoesNotMatchBaseVector() public view {
        bytes32 base = evidenceJson.readBytes32(".vectors.approval.expectedDigest");
        bytes32 changed = harness.hashApproval(CHAIN_ID, VERIFYING_CONTRACT, _fixtureApprovalChangedNonce());
        assertTrue(changed != base, "changed nonce produced the same digest as the base approval");
    }

    function test_WrongChainId_DoesNotMatchBaseVector() public view {
        bytes32 base = evidenceJson.readBytes32(".vectors.invoice.expectedDigest");
        bytes32 wrong = harness.hashInvoice(WRONG_CHAIN_ID, VERIFYING_CONTRACT, _fixtureInvoice());
        assertTrue(wrong != base, "wrong chainId produced the same digest as the base invoice");
    }

    function test_WrongVerifyingContract_DoesNotMatchBaseVector() public view {
        bytes32 base = evidenceJson.readBytes32(".vectors.invoice.expectedDigest");
        bytes32 wrong = harness.hashInvoice(CHAIN_ID, WRONG_VERIFYING_CONTRACT, _fixtureInvoice());
        assertTrue(wrong != base, "wrong verifyingContract produced the same digest as the base invoice");
    }

    // --- Same-fixture cross-check for the TS negative vectors too (belt and suspenders) ---

    function test_TsNegativeVectors_AlsoDivergeInSolidity() public view {
        bytes32 base = evidenceJson.readBytes32(".vectors.invoice.expectedDigest");
        bytes32 tsChangedAmount = evidenceJson.readBytes32(".negativeCases.invoiceChangedAmountDiffersFromBase.digest");
        bytes32 tsWrongChain = evidenceJson.readBytes32(".negativeCases.invoiceWrongDomainChainDiffersFromBase.digest");
        bytes32 tsWrongContract =
            evidenceJson.readBytes32(".negativeCases.invoiceWrongDomainContractDiffersFromBase.digest");
        assertTrue(tsChangedAmount != base, "TS-side changed-amount vector unexpectedly equals base");
        assertTrue(tsWrongChain != base, "TS-side wrong-chain vector unexpectedly equals base");
        assertTrue(tsWrongContract != base, "TS-side wrong-verifyingContract vector unexpectedly equals base");
    }
}
